name: build
on:
  push:
  pull_request_target:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    # Building and testing cannot work if the repository owner is not Xeeynamo
    # due to the missing secrets to clone the CI dependencies
    if: github.repository == 'Xeeynamo/ff7-decomp'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.25.3'
    - run: sudo apt-get install -y ninja-build 7zip binutils-mipsel-linux-gnu gcc-mipsel-linux-gnu
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v5
      with:
        ref: ${{ github.ref }}
        submodules: true
    - if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        submodules: true
    - run: make requirements
    - name: Check if code is formatted
      run: |
        make format
        git diff --exit-code
    - uses: actions/checkout@v5
      with:
        repository: xeeynamo/ff7-decomp-dependencies
        token: ${{ secrets.FF7_DECOMP_DEPENDENCIES_TOKEN }}
        path: tmp
    - run: |
        cat tmp/x* > tmp/ff7.7z
        7z x -sdel tmp/ff7.7z -odisks/
        rm tmp/*
        ls -la disks/
    - run: make build
    - name: Generate progress report
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: go run ./tools/builder report config/us.yaml build/report.json
    - name: Upload progress report
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: us_report
        path: build/report.json
